baseURL = "https://volartrix.xyz"
theme = "risotto"
title = "volartrix.xyz"
author = "RaphtikAtGHG"
copyright = "© [RaphtikAtGHG](https://github.com/RaphtikAtGHG)."
paginate = 3
languageCode = 'en-us'
contentDir = 'content'
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
enableEmoji = true
sectionPagesMenu = "main"

[menu]


[params]
noindex = false

[params.theme]
palette = "base16-dark"

[params.about]
title = "volartrix.xyz"
description = "The website for the volartrix project and other stuff"


[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/RaphtikAtGHG"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:info@volartrix.xyz"

[[params.socialLinks]]
icon = "fa-brands fa-paypal"
title = "Donate"
url = "https://paypal.me/raphaelwegmann"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup]
    [markup.tableOfContents]
        startLevel = 2
        endLevel   = 3
        ordered    = true